export const data = [
    {
        id: 0,
        titulo: "Biologia",
        descricao_1: "Biologia é a ciência natural que estuda, descreve, preserva e melhora a vida e os organismos vivos. Apesar de sua complexidade, certos conceitos unificadores a consolidam em um campo único e coerente. A biologia reconhece a célula como a unidade básica da vida, os genes como a unidade básica da hereditariedade e a evolução como o motor natural que impulsiona a origem e extinção das espécies. Além disso, reconhece que os organismos vivos possuem estruturação interna em compartimentos com funções específicas, seja a nível celular, anatômico, fisiológico ou de diversidade e nichos ecológicos. Os organismos vivos também podem ser vistos do ponto de vista físico e químico como sistemas abertos que sobrevivem transformando energia e diminuindo sua entropia local",
        imagem_1: "https://static.preparaenem.com/2022/10/biologia.jpg",
        descricao_2: "ciência que estuda a vida e os organismos vivos, sua estrutura, crescimento, funcionamento, reprodução, origem, evolução, distribuição, bem como suas relações com o ambiente e entre si; biociência, ciências biológicas [Compreende várias outras ciências especializadas, como, p.ex., a ecologia, a bioquímica, a genética, a zoologia e a botânica,para manter um o equilíbrio dinâmico vital, através de reações bioquímicas (homeostase). Por outro lado, organismos vivos também podem ser vistos sob o ângulo da produção econômica (produtos, processos, serviços e biotecnologias), ",
        imagem_2: "https://s1.static.brasilescola.uol.com.br/be/conteudo/images/a-biologia-estuda-vida-em-seus-mais-variados-aspectos-5626a8e531af7.jpg",
        img_w: "30%",
        img_h: "30%"
    },
    {
        id: 1,
        titulo: "Educação financeira",
        descricao_1: "A educação financeira é uma área transversal e Interdisciplinar cujo propósito é auxiliar indivíduos na escolha de seus rendimentos, em seus sonhos, no consumo sustentável, em suas decisões sobre investimentos, e na prevenção de situações problemáticas; não deve ser confundida com a matemática financeira, enquanto a primeira se trata de uma área que comunica com as outras como a economia, biologia (meio ambiente e saúde), história, sociologia, geografia, etc., a segunda é específica da matemática",
        imagem_1: "https://www.globalempregos.com.br/wp-content/uploads/2022/02/financas-1.jpg",
        descricao_2: "Desde o surgimento do sistema capitalista, as pessoas tiveram a necessidade de se adaptar ao novo conceito de dinheiro e a suas variáveis (mais complexas, comparativamente aos sistemas econômicos anteriores). As novas relações de troca, domínio e poder fundamentaram as bases econômico-sociais vigentes ainda nos dias de hoje.",
        imagem_2: "https://files.sunoresearch.com.br/p/uploads/2022/03/educacao-financeira-capa-1-1024x554.png",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 2,
        titulo: "Geografia",
        descricao_1: "Geografia (do grego γεωγραφία, geographia, literalmente descrição da terra) é uma área da ciência dedicado ao estudo responsável por examinar a superfície do planeta Terra e compreender todos os aspectos físicos e humanos deste. A primeira pessoa a usar a palavra γεωγραφία foi Eratóstenes (276–194 aC). A geografia é uma disciplina abrangente que busca uma compreensão da Terra e suas complexidades humanas e naturais  não apenas onde os objetos estão, mas também como eles mudaram e vieram a ser. Embora a geografia seja específica do planeta Terra, muitos conceitos podem ser aplicados de forma mais ampla a outros corpos celestes no campo da ciência planetária.",
        imagem_1: "https://blogger.googleusercontent.com/img/a/AVvXsEh_bd7wKaq3NqxAIcX2CxXr7ls5tSqqHq4-8M2jmbAMZ_YVrKHIt8J46kbB0M-4Quz089gObFTu2oczLXMMZDJ26x8URcDE0AKvdnUf1KSEs1kQEQF1DJg0WhNOUKEf-s2BUATkfQ0pfC7NH0lI7i5xcSrobrHcrJ50025HmxWV9XbFvNeDqbBbhrzteA=w1600",
        descricao_2: "A geografia é muitas vezes definida em termos de dois ramos: geografia humana e geografia física. A geografia humana está preocupada com o estudo das pessoas e suas comunidades, culturas, economias e interações com o meio ambiente, estudando suas relações com e através do espaço e lugar. A geografia física está preocupada com o estudo de processos e padrões no ambiente natural, como a atmosfera, hidrosfera, biosfera e geosfera. Para alguns, a Geografia também é uma prática humana de conhecer onde se vive,",
        imagem_2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlL2dh0g_pJQY1yLBvCh7HShODEwvkIxl7cKqtPDtTPS5KFfGuhGZCi3QHy4QJO1OIyr8&usqp=CAU",
        img_w: "30%",
        img_h: "30%",
    },
    {
        id: 3,
        titulo: "História",
        descricao_1: "História (do grego antigo ἱστορία, transl.: historía, que significa pesquisa, conhecimento advindo da (investigação)é a ciência que estuda o ser humano e sua ação no tempo e no espaço concomitantemente à análise de processos e eventos ocorridos no passado. O termo História também pode significar toda a informação do passado que foi guardada em todas as línguas por todo o mundo, por intermédio de registos históricos.",
        imagem_1: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Nikolaos_Gyzis_-_Historia.jpg/330px-Nikolaos_Gyzis_-_Historia.jpg",
        descricao_2: "A palavra história tem sua origem nas investigações de Heródoto; em grego antigo, o termo História é Ἱστορίαι (Historíai). Todavia, será Tucídides o primeiro a aplicar métodos críticos, como o cruzamento de dados e uso de diversas fontes diferentes. O estudo histórico começa quando o ser humano encontra os elementos de sua existência nas realizações dos seus antepassados. Esse estudo, do ponto de vista europeu, divide-se em dois grandes períodos: Pré-história e História.",
        imagem_2: "https://s1.static.brasilescola.uol.com.br/be/conteudo/images/historia-ciencia-que-estuda-os-acontecimentos-passados-acao-homem-no-tempo-5c23497443dd8.jpg",
        img_w: "30%",
        img_h: "30%",
    },
    {
        id: 4,
        titulo: "Ingles",
        descricao_1: "glês (English) é uma língua indo-europeia germânica ocidental que surgiu nos reinos anglo-saxônicos da Inglaterra e se espalhou para o que viria a tornar-se o sudeste da Escócia, sob a influência do reino anglo medieval da Nortúmbria. Após séculos de extensa influência da Grã-Bretanha e do Reino Unido desde o século XVIII, através do Império Britânico, e dos Estados Unidos desde meados do século XX,[4][5][6][7] o inglês tem sido amplamente disperso em todo o planeta, tornando-se a principal língua do discurso internacional ",
        imagem_1: "https://img.freepik.com/vetores-gratis/fundo-de-escola-de-ingles-desenhado-a-mao_23-2149483339.jpg?size=626&ext=jpg&ga=GA1.2.882365898.1680826360&semt=sph",
        descricao_2: "e uma língua franca em muitas regiões.[8][9] O idioma é amplamente aprendido como uma segunda língua e usado como língua oficial da União Europeia, das Nações Unidas e de muitos países da Commonwealth, bem como de muitas outras organizações mundiais. É o terceiro idioma mais falado em todo o mundo como primeira língua, depois do mandarim e do espanhol.",
        imagem_2: "https://cdn.wizard.com.br/wp-content/uploads/2020/06/03192344/palavras-em-ingles-britanico-e-ingles-americano-wizard.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 5,
        titulo: "Portugues",
        descricao_1: "A língua portuguesa, também designada português, é uma língua indo-europeia românica flexiva ocidental originada no galego-português falado no Reino da Galiza e no norte de Portugal. Com a criação do Reino de Portugal em 1139 e a expansão para o sul na sequência da Reconquista, deu-se a difusão da língua pelas terras conquistadas e mais tarde, com as descobertas portuguesas, para o Brasil, África e outras partes do mundo.",
        imagem_1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWVs0wkGpRhTA-jyfm-dXk2gVkMrDK2nuyHg&usqp=CAU",
        descricao_2: "O português foi usado, naquela época, não somente nas cidades conquistadas pelos portugueses, mas também por muitos governantes locais nos seus contatos com outros estrangeiros poderosos. Especialmente nessa altura a língua portuguesa também influenciou várias línguas.",
        imagem_2: "https://caminhoslanguages.com/wp-content/uploads/2020/07/brazilian-portuguese-vs-european-portuguese.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 6,
        titulo: "Matemática",
        descricao_1: "A matemática (dos termos gregos, μάθημα, transliterado máthēma, 'ciência', conhecimento' ou 'aprendizagem; e μαθηματικός, transliterado mathēmatikós, 'inclinado a aprender') é a ciência do raciocínio lógico e abstrato, que estuda quantidades (teoria dos números), espaço e medidas (geometria), estruturas, variações e estatística. Não há, porém, uma definição consensual por parte da comunidade científica. O trabalho matemático consiste em procurar e relacionar padrões, de modo a formular conjecturas[10] cuja veracidade ou falsidade é provada por meio de deduções rigorosas, a partir de axiomas e definições. A matemática desenvolveu-se principalmente na Mesopotâmia, no Egito, na Grécia, na Índia e no Oriente Médio.",
        img_w: "30%",
        img_h: "30%",
        imagem_1: "https://s2.glbimg.com/M37VWHlfn6FfGNevaf-gJdxROw4=/e.glbimg.com/og/ed/f/original/2019/06/28/math-1500720_1920.jpg",
        descricao_2: "Registros arqueológicos mostram que a matemática é tanto um fator cultural quanto parte da história do desenvolvimento da nossa espécie. Ela evoluiu por meio de contagens, medições, cálculos e do estudo sistemático de formas geométricas e movimentos de objetos físicos. Já as proposições mais abstratas, que envolvem a argumentação lógica, surgiram com os matemáticos gregos, há aproximadamente 300 a.C., notadamente com a obra Os Elementos, de Euclides. A necessidade de maior rigor foi percebida e estabelecida por volta do início do século XVIII.",
        imagem_2: "https://2.bp.blogspot.com/-Q7JTCORrlh4/W5pT4DWaFEI/AAAAAAAAP5E/J6kV9QALvtg0X49X1Sabxcjjoxb0hBKbACLcBGAs/s1600/Afinal%252C%2Bpara%2Bque%2Bserve%2Ba%2BMatem%25C3%25A1tica.jpg",

    },
    {
        id: 7,
        titulo: "Projeto de vida",
        descricao_1: "O que é o Projeto de Vida? O Projeto de Vida é uma iniciativa cujo objetivo é criar uma ponte entre quem o aluno é e quem ele quer ser. Por meio desse planejamento, o aluno ganha uma melhor compreensão sobre os interesses profissionais, sociais e pessoais que compõem sua personalidade.",
        imagem_1: "https://programabene.com.br/wp-content/uploads/2020/08/apresentacao_pv.png",
        descricao_2: "Ou seja, com o Projeto de Vida a escola trabalha não apenas a vida acadêmica de seus estudantes, como também incentiva o desenvolvimento de competências socioemocionais que os ajudarão a se preparar para o futuro.",
        imagem_2: "https://www.correiodosmunicipios-al.com.br/wp-content/uploads/2022/06/img6.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 8,
        titulo: "quimica",
        descricao_1: "Química é a ciência que estuda a composição, estrutura, propriedades da matéria, as mudanças sofridas por ela durante as reações químicas e a sua relação com a energia. É considerada uma ciência exata e é chamada muitas vezes de ciência central porque é a ponte entre outras ciências naturais como a física, matemática e a biologia. A química possui papel fundamental no desenvolvimento tecnológico, pois a utilização dos conceitos e técnicas dessa ciência permite a obtenção de novas substâncias, além de preocupar-se com a prevenção de danos e exploração sustentável do meio ambiente.",
        imagem_1: "https://s1.static.brasilescola.uol.com.br/be/conteudo/images/o-que-fisica-565d9c383e603.jpg",
        descricao_2: "As áreas da química são agrupadas em quatro grandes divisões, a saber: química inorgânica (estuda a matéria inorgânica), química orgânica (estuda os compostos de carbono), físico-química (compreende os aspectos energéticos e cinéticos dos sistemas químicos e suas transformações em escalas macroscópicas, e atômico-molecular), e química analítica (analisa materiais e ajuda a compreender a sua composição e quantidade de sistemas químicos). Áreas interdisciplinares e complementares incluem bioquímica, ensino de química, e química ambiental.",
        imagem_2: "https://conceitos.com/wp-content/uploads/ciencia/Fisica-Classica.jpg",
        img_w: "20%",
        img_h: "20%",
    },
    {
        id: 9,
        titulo: "Sociologia",
        descricao_1: "A Sociologia é a ciência que estuda a sociedade e os fenômenos que nela ocorrem sejam eles culturais, econômicos, religiosos. A sociologia se ocupa basicamente de cinco elementos: a estrutura social, os grupos sociais, a família, as classes sociais e os papéis que o indivíduo ocupa em sociedade",
        imagem_1: "https://static.todamateria.com.br/upload/oq/ue/o-que-e-sociologia-og.jpg",
        descricao_2: "A sociologia busca explicar os vários fatores que diferenciam o comportamento humano ou, pelo contrário, porque grupos sociais diversos tendem a comportar-se de maneira semelhante.",
        imagem_2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo_P6kz7td6nGzRUlkJ9JH-_Y0tANJkulUXg&usqp=CAU",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 10,
        titulo: "Analise e projeto",
        descricao_1: "Enquanto que o modelo de análise representa o “mundo real”, ou seja o domínio do negócio, o modelo de projeto representa a solução do problema, do ponto de vista dos componentes necessários para construir a solução e seus relacionamentos. O modelo de análise é refinado e transformado no modelo de projeto.",
        imagem_1: "https://i.ytimg.com/vi/-1DRKmh-44s/maxresdefault.jpg",
        descricao_2: "A primeira coisa que se deve pensar quando se fala em analisar um sistema é saber para que ele vai servir. Por exemplo, você está desenvolvendo um sistema de cadastro de clientes, sendo que talvez, a necessidade do comerciante/empresa seja diferente da visão de um desenvolvedor novato.",
        imagem_2: "https://1.bp.blogspot.com/-fjhl8UHgPc8/VwIazYMqX4I/AAAAAAAARNc/9Z1u0HaQJ_A_vQwU_J2Gsief27PwAvw8w/s1600/BANNER.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 11,
        titulo: "Banco de dados",
        descricao_1: "Se você tem um site (em WordPress ou outra plataforma) ou já pensou em construir um, certamente, já ouviu falar sobre banco de dados. Os banco de dados podem ser utilizados em diversos contextos, desde o controle de informações do RH, até o armazenamento e gestão da informação de sites e blogs.",
        imagem_1: "https://solvimm.com/wp-content/uploads/2019/11/Destacada_Qual_tipo_de_Banco_de_Dados_utilizar.png",
        descricao_2: "Um banco de dados é uma coleção organizada de informações - ou dados - estruturadas, normalmente armazenadas eletronicamente em um sistema de computador. Um banco de dados é geralmente controlado por um sistema de gerenciamento de banco de dados (DBMS). Juntos, os dados e o DBMS, juntamente com os aplicativos associados a eles, são chamados de sistema de banco de dados, geralmente abreviados para apenas banco de dados.",
        imagem_2: "http://ehgomes.com.br/disciplinas/bdd/imagens/2021db.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 12,
        titulo: "Ciencias da computaçao",
        descricao_1: "Ciência da computação é a ciência que estuda as técnicas, metodologias, instrumentos computacionais e aplicações tecnológicas, que informatizem os processos e desenvolvam soluções de processamento de dados de entrada e saída pautados no computador.",
        imagem_1: "https://images.educamaisbrasil.com.br/content/noticias/conheca-o-mercado-de-trabalho-de-ciencia-da-computacao_g.jpg",
        descricao_2: "Enquanto ciência, classifica-se como ciência exata, apesar de herdar elementos da lógica filosófica aristotélica, tendo por isto um papel importante na formalização matemática de algoritmos, como forma de representar problemas decidíveis, i.e., os que são susceptíveis de redução a operações elementares básicas, capazes de serem reproduzidas através de um dispositivo qualquer capaz de armazenar e manipular dados",
        imagem_2: "https://blog.uniube.br/hubfs/Imported_Blog_Media/Conheça-área-de-Ciência-da-Computação.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 13,
        titulo: "Prog front-end",
        descricao_1: "O Front-end está muito relacionado com a interface gráfica do projeto. Ou seja, é onde se desenvolve a aplicação com a qual o usuário irá interagir diretamente, seja em softwares, sites, aplicativos, etc. Portanto, é essencial que o desenvolvedor tenha uma preocupação com a experiência do usuário.Dev front-end é um termo muito utilizado para identificar profissionais que se especializaram especificamente nessa área. ",
        imagem_1: "https://www.alura.com.br/artigos/assets/como-iniciar-estudos-no-front-end/capa-como-iniciar-estudos-no-front-end.jpg",
        descricao_2: "Além disso, apesar de envolver a interface do projeto, o programador front-end não é formado em design. A diferença entre os dois é que o desenvolvedor não desenha visualmente a interface.    Na verdade, no desenvolvimento front-end, o profissional irá mexer com o código em si, projetando com quais ferramentas o usuário irá interagir. Por esse motivo, é importante ter essa diferença em mente quando falamos sobre o assunto",
         imagem_2: "https://blog.b2bstack.com.br/wp-content/uploads/2022/01/front-end-banner.jpg",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    },
    {
        id: 14,
        titulo: "Prog mobile",
        descricao_1: "Para explicar de uma maneira simples, a programação mobile é utilizada para o desenvolvimento de aplicativos, mas ela também pode ser utilizada para em qualquer tipo de desenvolvimento para dispositivo móvel   No geral essa programação envolve a criação de aplicativos para smartphones, tablets, smartwatches e entre outros dispositivos que também utilizam algum tipo de sistema operacional móvel.Além disso, é importante destacar que a programação mobile precisa estar integrada com toda a equipe.",
        
        imagem_1: "https://macmagazine.com.br/wp-content/uploads/2019/10/02-desenvolvimento-mobile.jpg",
        descricao_2: "Esse profissional fica responsável por projetar, desenvolver e implementar os aplicativos móveis.Entre as suas responsabilidades o desenvolvedor deve viabilizar a técnica e cumprir com os requisitos (guidelines) operadores das apps stores.",
         imagem_2: "https://becode.com.br/wp-content/uploads/2017/01/Trajetoria-Mobile-Dev.png",
        img_w: "30%",
        img_h: "30%",
        button_event: onclick(),
    }
]



function onclick(){
    console.log("tu é foda alek!");
}